### PR TITLE
CORS on passthrough setup

### LINKED ISSUE #8: CORS option
@rclark over in https://github.com/mapbox/wildfire-demo-public/blob/master/cloudformation/wildfire-demo-public.template.js#L341-L375 you set up the API Gateway to handle CORS requests. It would be nice if we could build this feature into hookshot.

### PR DESCRIPTION
**Pull request by rclark**
This PR adds CORS support to hookshot's passthrough option. #8 suggested making this optional, but for now let's just add it whenever you use the passthrough option.

This PR also adds CloudFormation logic to cycle the Deployment resource every time you update a cloudformation stack (cc @emilymdubois I recall that you'd run up against this). This should make template changes visible on the API right after a stack update.

@davidtheclark -- I got this to the point that in the API Gateway console, testing the OPTIONS method is successful and its not giving internal server errors. However, when I try and make an OPTIONS request manually I get a 403. Possibly that is me making a bad OPTIONS request, or could be that something is still garbled.

Do you have a system you can drop this into and easily see if the browser also gets a 403 when trying to pre-flight a POST request?

fixes #8

### CODE REVIEW

**Comment by davidtheclark** [comment]
This should close #9, too, which is about refreshing the deployment name.

@rclark: If I try to install this branch and then deploy a stack, I'm blocked by the error `Expected version mapbox/hookshot#passthrough-cors of @mapbox/hookshot but found 2.1.0`. Is there a way around this?

**Comment by rclark** [comment]
Use a tarball URL instead. 

https://github.com/mapbox/hookshot/tarball/passthrough-cors

**Comment by davidtheclark** [comment]
@rclark I can confirm that I'm seeing the same problem with this implementation as I was with my own — 200 responses in the AWS console, but 403 responses from curl and in the browser.

**Comment by rclark** [comment]
Fixed the 403 issue --> hookshot was producing a stack output that was incorrect, leading us to make our POST and OPTIONS requests to the wrong URL.

**Pull request merged**
