### PR TITLE
Passthrough function for unadulterated webhooks

### PR DESCRIPTION
**Pull request by rclark**
Exports a `.passthrough` function: you provide a Lambda function name, and this gives you the API Gateway and a URL that will invoke your function directly. Where the old function was designed to verify that the webhook payload came from github, this function just passes the payload straight to your Lambda. 

Once this merges, I should probably change the name of the repository. Any better ideas @davidtheclark?

### CODE REVIEW

**Comment by davidtheclark** [comment]
So the idea is to make a more generic endpoint, which can receive POSTs from anything and just send them right on through to the Lambda function?

`aws-webhook` might make sense?

**Comment by rclark** [comment]
yeahhhh. But how boring is that?

**Comment by davidtheclark** [comment]
How about "hook-eye". Lots of good things about this name:

- You could design a mascot that mocks Hawkeye.
- It evokes the "eye" some things have that you put hooks into, like tarps. (From definition of "eye": "a small metal loop into which a hook is fitted as a fastener on a garment".)
- It evokes images of a person catching a fishhook in their eye.

It's not very descriptive, though.

**Comment by rclark** [comment]
hookshot

While an animated gif might be a decent way to argue for "Hookshot" as a library name, I will not accept similar arguments for "hookeye".

**Comment by davidtheclark** [comment]
Two other ideas for relevant GIFs:

b4zgcopthyxl2

eye

**Comment by emilymdubois** [comment]
Also throwing `skyhook` into the mix:
- It evokes images of technology and clouds, both of which are pertinent.
- Similar to an airplane rescuing a person on the ground via a cable, this repo is cool.

skyhook

**Comment by rclark** [comment]
image

We're going with hookshot.

**Comment by emilymdubois** [comment]
Devastated.

**Comment by rclark** [comment]
I voted for skyhook.

**Pull request merged**
